# Site settings
title: Takaro - gry planszowe Olsztyn
email: sklep@takaro.pl
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://takaro.pl" # the base hostname & protocol for your site

twitter_username:
facebook_username: takarosklep

# Build settings
markdown: kramdown
